; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_l432kc]
platform = ststm32
board = nucleo_l432kc
framework = stm32cube

; build_type = debug
; monitor_port = /dev/ttyACM0
; monitor_speed = 9600


build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32L432xx

board_build.stm32cube.startup_file = startup_stm32l432xx.s
board_build.stm32cube.system_file  = system_stm32l4xx.c
